{{- if .Values.focusServer.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "focus-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "focus-server.name" . }}
    helm.sh/chart: {{ include "focus-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  ingressClassName: {{ .Values.focusServer.ingress.ingressClassName | quote }}
  rules:
    {{- range .Values.focusServer.ingress.rules }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "focus-server.fullname" $ }}
                port:
                  number: {{ $.Values.focusServer.service.port }}
          {{- end }}
    {{- end }}
  {{- if .Values.focusServer.ingress.tls }}
  tls:
    {{- range .Values.focusServer.ingress.tls }}
    - hosts:
        {{- range .hosts }}
          - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
