{{- /*
This file creates the necessary RBAC resources.
Values expected in values.yaml:
  cleanupService.serviceAccountName - name of the service account for cleanup
*/ -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: kubectl-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "delete", "create", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "delete", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "delete", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: kubectl-sa
    namespace: default
roleRef:
  kind: Role
  name: kubectl-role
  apiGroup: rbac.authorization.k8s.io
