apiVersion: v1
kind: ServiceAccount
metadata:
  name: focus-server-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: focus-server-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "create"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: focus-server-sa
  namespace: default
roleRef:
  kind: Role
  name: focus-server-role
  apiGroup: rbac.authorization.k8s.io
