{{- if ( .Values.global.is_dev | default false ) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "player.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "player.name" . }}
    helm.sh/chart: {{ include "player.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.player.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "player.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "player.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: player
          image: "{{ .Values.player.image.repository }}:{{ .Values.player.image.tag }}"
          imagePullPolicy: {{ .Values.player.image.pullPolicy }}
          workingDir: {{ .Values.player.workingDir | quote }}
          env:
            - name: PRISMA_RABBIT_MACHINE_NAME
              value: {{ .Values.player.env.PRISMA_RABBIT_MACHINE_NAME | quote }}
            - name: PRISMA_CERTIFICATES
              value: {{ .Values.player.env.PRISMA_CERTIFICATES | quote }}
            - name: PRISMA_CONFIG
              value: {{ .Values.player.env.PRISMA_CONFIG | quote }}
          command: {{ toYaml .Values.player.command | nindent 12 }}
          volumeMounts:
            - name: certs
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: debug-env-volume
              mountPath: {{ .Values.player.volumeMounts.debugEnv.mountPath | quote }}
            - name: prisma-config-volume
              mountPath: {{ .Values.player.volumeMounts.prismaConfig.mountPath | quote }}
            - name: storage-san-volume
              mountPath: {{ .Values.player.volumeMounts.storageSan.mountPath | quote }}
      terminationGracePeriodSeconds: {{ .Values.player.terminationGracePeriodSeconds }}
      volumes:
        {{- if .Values.debug-env.enabled }}
        - name: debug-env-volume
          hostPath:
            path: {{ .Values.debug-env.mountPath | quote }}
            type: Directory
        {{ - end }}
        - name: prisma-config-volume
          configMap:
            name: prisma-config
        - name: recordings
          persistentVolumeClaim:
            claimName: recordings-pvc
        - name: certs
          projected:
            sources:
              - secret:
                  name: {{ .Values.player.tlsSecret.name }}
                  items:
                    - key: ca.crt
                      path: {{ .Values.player.tlsSecret.items.caCrtPath }}
                    - key: tls.crt
                      path: {{ .Values.player.tlsSecret.items.tlsCrtPath }}
                    - key: tls.key
                      path: {{ .Values.player.tlsSecret.items.tlsKeyPath }}

{{- end }}