# ansible/inventory/group_vars/panda-dev.yml

# Where we store the versions
versions_file: "../sites_versions/panda-dev-versions.yml"

# If you still want to toggle roles here, keep them:
enable_create_worker_node: true
enable_create_master_node: false
enable_apt_install: false
enable_network_setup: false
enable_docker_load: false
enable_helm_install: false
enable_netplan_config: false


configurations:
  # PROXMOX CONNECTION PARAMS #
  system_type: 'dev'
  proxmox_host_ip: "10.50.1.101"
  proxmox_user: "root@pam"
  proxmpx_user_password: "PASSW0RD"
  proxmox_node: "shakedonprem"
  installation_mode: offline  # or online
  # PROXMOX CONNECTION PARAMS #

  # Communication #
  getaway_ip: "10.50.1.1"
  # Communication #

  # vms configuration #
  vms:
    - workernode-panda-west:
        ip: "10.50.1.152"
        dev: true
        type: workernode
        gpu: true

    - masternode-panda-west:
        name: "masternode-panda-west"
        ip: "10.50.1.151"
        dev: true
        type: workernode
        gpu: false
  # vms configuration #

  machines:
    interrogator:
      # PROXMOX CONNECTION PARAMS #
      system_type: 'prod'
      proxmox_host_ip: "10.50.2.101"
      proxmox_user: "root@pam"
      proxmpx_user_password: "PASSW0RD"
      installation_mode: offline  # or online
      # PROXMOX CONNECTION PARAMS #
