# ansible/inventory/group_vars/panda-dev.yml

# Where we store the versions
versions_file: "../offline_deploy/panda-dev-versions.yml"

# If you still want to toggle roles here, keep them:
enable_apt_install: false
enable_docker_load: true
enable_helm_install: false
enable_netplan_config: false

# Netplan config (if you want to keep it separate)
netplan_config_file: "panda-dev-netplan.yaml"
