# ansible/inventory/group_vars/panda-dev.yml

# Path to offline artifacts
offline_artifact_path: ../offline_deploy/

# Where we store the versions
versions_file: "../offline_deploy/panda-dev-versions.yml"

# If you still want to toggle roles here, keep them:
enable_helm_install: false
enable_netplan_config: false

# Netplan config (if you want to keep it separate)
netplan_config_file: "panda-dev-netplan.yaml"

# If you're leaving apt-install always on, you don't need "enable_apt_install" 
# but you could specify it if your logic requires it.

