
create-vms: true

# PROXMOX CONNECTION PARAMS #
system_type: 'dev'
proxmox_host_ip: "10.50.0.24"
proxmox_user: "root@pam"
proxmox_user_password: "Pa$$w0rd!"
proxmox_node: "vm1"
installation_mode: offline  # or online

# vms configuration #
vms:
  workernode-shaked:
    name: "worker-node-shaked"
    ip: "10.50.0.152"
    vmid: 106
    dev: true
    type: workernode
    gpu: true

  masternode-shaked:
    name: "masternode-shaked"
    ip: "10.50.0.151"
    vmid: 107
    dev: true
    type: workernode
    gpu: false