---
# handlers/main.yml

- name: reload systemd daemon
  become: yes
  systemd:
    daemon_reload: yes

- name: restart k3s-agent service
  become: yes
  systemd:
    name: k3s-agent
    state: restarted
