- name: Debug - Setting the DCHP
  debug:
    msg: "{{ network_adapter }}"

- name: Setup network with DHCP (if enabled in the configuration)
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host_ip }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_user_password }}"
    node: "{{ proxmox_node }}"
    name: "{{ vm_params.name | default(vm_name) }}"
    net:
      net1: "virtio,bridge=vmbr0"
    ipconfig:
      ipconfig1: "ip=dhcp"                   # Can be configurable but for now it is like that
    update: True                               # Must be here to apply the update
    update_unsafe: True                        # Must be here to apply the update
  delegate_to: localhost

