- name: Process data transfer for each entry
  include_tasks: data_transfer_entry.yml
  loop: "{{ data_transfer }}"
  loop_control:
    loop_var: dt
  vars:
    pvc_name: "{{ dt.pvc_name }}"
    host_mount: "{{ dt.host_mount }}"
    host_path: "{{ dt.host_path }}"
    dest_path: "{{ dt.dest_path }}"
    container_name: "data-transfer-{{ dt.pvc_name }}"
    pod_name: "data-transfer-{{ dt.pvc_name }}"

