- block:
    - name: Run helmfile sync with injected environment variables using -f flag
      command: "helmfile -f helmfile.yaml sync --concurrency=1 --skip-deps"
      args:
        chdir: "{{ artifact.path }}/linux-infra/projects/{{ helm_spec.project }}"
      environment:
        PROJECT_NAME: "{{ helm_spec.project }}"
        LINUX_USER: "{{ linux_user.user_name }}"
        THREE_FIRST_OCTETS: "{{ helm_spec.threeFirstOctets }}"
        KUBECONFIG: "/home/{{ linux_user.user_name }}/.kube/config"
      register: helmfile_output

  always:
    - name: Ensure output directory exists on the controller
      file:
        path: "{{ artifact.path }}/helmfile_outputs"
        state: directory
        mode: '0755'