- block:
    - name: Run helmfile sync with injected environment variables using -f flag
      command: "helmfile -f helmfile.yaml sync --concurrency=1 --skip-deps"
      args:
        chdir: "/home/{{ artifact_path.linux_user }}/linux-infra/projects/{{ helm_spec.project }}"
      environment:
        PROJECT_NAME: "{{ helm_spec.project }}"
        OFFLINE_DEPLOY: "{{ artifact_path.offline_deploy }}"
        LINUX_USER: "{{ artifact_path.linux_user }}"
        THREE_FIRST_OCTETS: "{{ helm_spec.threeFirstOctets }}"
        KUBECONFIG: "/home/{{ artifact_path.linux_user }}/.kube/config"
      register: helmfile_output

  always:
    - name: Ensure output directory exists on the controller
      file:
        path: "/home/{{ artifact_path.linux_user }}/helmfile_outputs"
        state: directory
        mode: '0755'