- name: Check if imported images directory exists
  stat:
    path: "/home/{{ artifact_path.linux_user }}/{{ artifact_path.offline_deploy }}/helm_charts/downloaded_helm_charts/"
  register: imported_charts

- import_tasks: helm_pull.yml
  when: not imported_charts.stat.exists

- name: Check if imported images directory exists
  stat:
    path: "/home/{{ artifact_path.linux_user }}/{{ artifact_path.offline_deploy }}/linux-infra/"
  register: linux_infra

- name: Ensure repository is present and up-to-date
  git:
    repo: "https://{{ git_username | urlencode }}:{{ git_password | urlencode }}@github.com/PrismaPhotonics/linux-infra.git"
    dest: "/home/{{ artifact_path.linux_user }}/{{ artifact_path.offline_deploy }}/linux-infra/"
    version: main
  when: not linux_infra.stat.exists

- import_tasks: dos2unix_all_scripts.yml

- import_tasks: helm_install.yml