---
- name: Find all .sh files under linux-infra recursively
  find:
    paths: "/home/{{ versions_data.linuxUser }}/linux-infra/"
    patterns: "*.sh"
    recurse: yes
  register: sh_files

- name: Run dos2unix on each found .sh file
  command: dos2unix "{{ item.path }}"
  loop: "{{ sh_files.files }}"
  when: sh_files.matched > 0

- name: Run helmfile sync with injected environment variables using -f flag
  command: "helmfile -f helmfile.yaml sync --concurrency=1 --skip-deps"
  args:
    chdir: "/home/{{ versions_data.linuxUser }}/linux-infra/projects/{{ versions_data.project }}"
  environment:
    PROJECT_NAME: "{{ versions_data.project }}"
    OFFLINE_DEPLOY: "{{ versions_data.offlineDeploy }}"
    LINUX_USER: "{{ versions_data.linuxUser }}"
    THREE_FIRST_OCTETS: "{{ versions_data.threeFirstOctets }}"
    KUBECONFIG: "/home/{{ versions_data.linuxUser }}/.kube/config"
  register: helmfile_output
  ignore_errors: yes

- name: Ensure output directory exists on the controller
  file:
    path: "/home/{{ versions_data.linuxUser }}/helmfile_outputs"
    state: directory
    mode: '0755'

- name: Display helmfile command output
  debug:
    msg: "To debug check helmfile output go to /home/{{ versions_data.linuxUser }}/helmfile_outputs/helmfile_output.txt"

- name: Write helmfile command output 
  copy:
    dest: "/home/{{ versions_data.linuxUser }}/helmfile_outputs/helmfile_output.txt"
    content: "{{ helmfile_output.stderr }}"

- name: Display helmfile command output
  debug:
    msg: "Output not formatted {{ helmfile_output.stderr }}"

- name: Fail the playbook if helmfile sync encountered an error
  fail:
    msg: "helmfile sync failed with exit code {{ helmfile_output.rc }}. Check the output file for details."
  when: helmfile_output.rc != 0
  
