- name: Include setup-artifiacts-for-helm-install role
  include_role:
    name: setup-artifiacts-for-helm-install

- name: Include setup-openebs role
  include_role:
    name: setup-openebs

- name: Include data-tranfer role if data_transfer is not empty
  include_role:
    name: data-transfer
  when: data_transfer | length > 0

- import_tasks: helm_install.yml
