---
- name: Find all .sh files under linux-infra recursively
  find:
    paths: "/home/{{ versions_data.linuxUser }}/linux-infra/"
    patterns: "*.sh"
    recurse: yes
  register: sh_files

- name: Run dos2unix on each found .sh file
  command: dos2unix "{{ item.path }}"
  loop: "{{ sh_files.files }}"
  when: sh_files.matched > 0

- name: Run helmfile sync with injected environment variables using -f flag
  command: "helmfile -f helmfile.yaml sync --concurrency=1 --skip-deps"
  args:
    chdir: "/home/{{ versions_data.linuxUser }}/linux-infra/projects/{{ versions_data.project }}"
  environment:
    PROJECT_NAME: "{{ versions_data.project }}"
    OFFLINE_DEPLOY: "{{ versions_data.offlineDeploy }}"
    LINUX_USER: "{{ versions_data.linuxUser }}"
    THREE_FIRST_OCTETS: "{{ versions_data.threeFirstOctets }}"
    KUBECONFIG: "/home/{{ versions_data.linuxUser }}/.kube/config"
  register: helmfile_output

- name: Display helmfile command output
  debug:
    msg: "{{ helmfile_output.stdout }}"
