--- 
- name: Run helmfile sync with injected environment variables
  command: helmfile sync --concurrency=1 --skip-deps
  environment:
    PROJECT_NAME: "{{ project }}"
    OFFLINE_DEPLOY: "{{ offlineDeploy }}"
    LINUX_USER: "{{ linuxUser }}"
    THREE_FIRST_OCTETS: "{{ threeFirstOctets }}"

