default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Git style
      - id: check-added-large-files
      - id: check-merge-conflict
        args: [ '--assume-in-merge' ]
      - id: check-vcs-permalinks
      - id: forbid-new-submodules

      # Common errors
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [ '--markdown-linebreak-ext=md' ]
        exclude: CHANGELOG.md
      - id: check-yaml
      - id: check-executables-have-shebangs

      # Cross-platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [ '--fix=lf' ]

      # Security
      - id: detect-aws-credentials
        args: [ '--allow-missing-credentials' ]
      - id: detect-private-key

      # Common config formats
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: sort-simple-yaml

  # Shell formatting and check
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shfmt
        args: [ '-l', '-i', '2', '-ci', '-sr', '-w' ]
      - id: shellcheck

  # TODO: This needs work - fails on trying to fetch "local" downloaded_helm_charts
  # This means it needs staging prep to run. no bueno.
#  - repo: local
#    hooks:
#      - id: helmfile-lint
#        name: helmfile lint
#        entry: helmfile lint --file **/*/helmfile.yaml
#        language: system
#        pass_filenames: false

  # TODO: Enable this separately after everything else passes
  # Ansible lint - See .ansible-lint for configuration
#  - repo: https://github.com/ansible/ansible-lint.git
#    rev: v25.1.3
#    hooks:
#      - id: ansible-lint
#        args: [ 'ansible' ]
#        verbose: true

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies: [ "tomli" ]

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-toml
        args: [ --autofix, --no-sort ]
      - id: pretty-format-yaml
        args: [ --autofix, --indent, '2', '--offset', '2', --preserve-quotes ]
