
- name: Backup existing Docker daemon.json (if exists)
  copy:
    src: /etc/docker/daemon.json
    dest: /etc/docker/daemon.json.bak
    remote_src: yes
  ignore_errors: yes
  become: yes

- name: Configure Docker daemon storage driver and insecure registries
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "storage-driver": "zfs",
        "insecure-registries": ["{{ versions_data.dockerRegistryAddress }}"]
      }
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Reload systemd configuration
  command: systemctl daemon-reload
  become: yes

- name: Restart Docker service
  service:
    name: docker
    state: restarted
  become: yes