- name: Gather Docker images info
  community.docker.docker_image_info:
  register: docker_info

- name: Build list of Docker images (repository:tag)
  set_fact:
    docker_images_list: >
      {{
        docker_info.images
        | map(attribute='RepoTags')
        | flatten
        | select('defined')
        | list
      }}

- name: Mirror Docker images to local registry with logging
  include_tasks: docker_mirroring_item.yml
  loop: "{{ docker_images_list | reject('match', '^' + versions_data.dockerRegistryAddress) | list }}"
  loop_control:
    loop_var: current_image