---
- name: Process data transfer for each entry
  block:
    - include_tasks: helm_template.yml
    - include_tasks: extract_and_apply_pvc.yml
    - include_tasks: data_transfer.yml
  loop: "{{ data_transfer }}"
  loop_control:
    loop_var: dt
  vars:
    chart_name: "{{ dt.chart_name }}"        
    release_name: "{{ dt.chart_release }}"            
    stack_path: "{{ artifact_path }}/linux-infra/stacks/{{ dt.stack_name }}"
    pvc_name: "{{ dt.pvc_name }}"
    src_directory: "{{ dt.src }}"
    dest_directory: "{{ dt.dest }}"
    linux_user_name: "{{ linux_user_name }}"
    project_name: "{{ project_name }}"
    three_first_octets: "{{ three_first_octets }}"
    artifact_path: "{{ artifact_path }}"
