filebeat:
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: filestream
        paths:
          - /var/log/syslog
          - /var/log/auth.log
        symlinks: true
        processors:
          - add_host_metadata:
              netinfo.enabled: true
          - add_fields:
              target: ''
              fields:
                type: syslog
                
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            hints.enabled: true

            hints.default_config:
              type: container
              paths:
                - /var/log/containers/*${data.kubernetes.container.id}.log

      output.logstash:
        hosts: ["logstash-logstash:5044"]

  resources:
      requests:
        cpu: "200m"
        memory: "200Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

  tolerations:
    - key: ""
      operator: "Exists"
      effect: "NoSchedule" 


  image: localhost:5000/docker.elastic.co/beats/filebeat
  imageTag: 8.5.1
  imagePullPolicy: IfNotPresent