enable_offline_apt_repo: false
enable_apt_install: true
enable_zfs_dataset_creation: true
enable_os_tools_install: true
enable_k3s_install: true
enable_drivers_install: true
enable_gpu_driver_uninstall: false
enable_configure_registry_mirroring: true
enable_helm_install: true