gpu_driver_version: '10.10.10'


enable_apt_install: true
enable_gpu_driver_install: true
enable_gpu_driver_uninstall: false
enable_network_setup: false
enable_docker_load: false
enable_helm_install: false


enable_netplan_config: false
