---
- name: Ensure local repo directory exists
  file:
    path: "{{ offline_deploy_path }}/apt/deb_packages/"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Fix permissions so '_apt' user can read repo files
  file:
    path: "{{ offline_deploy_path }}/apt/deb_packages/"
    recurse: yes
    owner: root
    group: root
    mode: '0755'

- name: Configure local repository as the only active source
  block:
    - name: Backup current sources.list
      copy:
        src: /etc/apt/sources.list
        dest: /etc/apt/sources.list.bak

    - name: Write new sources.list with local repo and commented original content
      shell: |
        {
          echo 'deb [trusted=yes] file://{{ offline_deploy_path }}/apt/deb_packages ./';
          echo "";
          echo "# ----- Original sources.list (commented) -----";
          sed 's/^/# /' /etc/apt/sources.list.bak;
        } > /etc/apt/sources.list
      args:
        executable: /bin/bash

    - name: Comment out all active lines in each file under /etc/apt/sources.list.d/
      shell: |
        for file in /etc/apt/sources.list.d/*; do
          if [ -f "$file" ]; then
            sed -i 's/^\([^#]\)/#\1/' "$file"
          fi
        done
      args:
        executable: /bin/bash

    - name: Run apt-get update to refresh package lists
      apt:
        update_cache: yes

  when: enable_local_repo | default(true)
