grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: "nginx"
    path: /grafana  
  adminUser: admin
  image:
    repository: 262399703539.dkr.ecr.eu-central-1.amazonaws.com/grafana-iec
    tag: on-prem2 
    env:
      GF_PATHS_PLUGINS: "/data/grafana/plugins"
  grafana.ini:
    paths:
      plugins: /data/grafana/plugins
    users:
      allow_sign_up: False
      auto_assign_org_role: Viewer
      default_theme: dark
    emails:
      welcome_email_on_sign_up: False
    auth:
      disable_login_form: false
      login_cookie_name: grafana_session
      login_maximum_inactive_lifetime_duration: 6h
      login_maximum_lifetime_duration: 6h
      token_rotation_interval_minutes: 10
    auth.anonymous:
      enabled: false
      org_name: "Main Org."
      org_role: Viewer
    server:
      domain: localhost
      root_url: https://localhost/grafana/
      serve_from_sub_path: true
    analytics:
      reporting_enabled: "True"
    dashboards:
      versions_to_keep: 20
    dashboards.json:
      enabled: true
      path: /etc/grafana/provisioning/dashboards
    alerting:
      enabled: true
      execute_alerts: True
    log:
      mode: console, file
      level: info
prometheus:
  server:
    persistentVolume:
      enabled: true
  prometheusSpec:
    retentionSize: "49GB"
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs: |
      - job_name: prisma-external
        scheme: http
        static_configs:
          - targets:
            - 10.10.10.2:9273
      - job_name: prisma-external-tls
        scheme: https
        tls_config:
          insecure_skip_verify: true
        static_configs:
          - targets:
            - 10.10.10.2:9273
        basic_auth:
          username: prisma
          password: ShowMeWhereItHurts
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-zfspv
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
alertmanager:
  enabled: false