- name: Ensure /etc/docker directory exists
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes
  
- name: Configure Docker daemon storage driver and insecure registries
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "storage-driver": "zfs",
        "insecure-registries": ["{{ docker_registry_address }}"]
      }
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Reload systemd configuration
  command: systemctl daemon-reload
  become: yes

- name: Restart Docker service
  service:
    name: docker
    state: restarted
  become: yes