---
- name: Set AWS access key
  command: aws configure set aws_access_key_id "{{ aws_access_key }}"
  when: aws_access_key is defined

- name: Set AWS secret key
  command: aws configure set aws_secret_access_key "{{ aws_secret_key }}"
  when: aws_secret_key is defined

- name: Set default AWS region
  command: aws configure set default.region "{{ aws_region }}"

- name: Login to AWS ECR
