---
- name: Set AWS access key
  command: aws configure set aws_access_key_id "{{ aws_access_key }}"
  when: aws_access_key is defined

- name: Set AWS secret key
  command: aws configure set aws_secret_access_key "{{ aws_secret_key }}"
  when: aws_secret_key is defined

- name: Set default AWS region
  command: aws configure set default.region "{{ aws_region }}"

- name: Login to AWS ECR
  shell: aws ecr get-login-password --region "{{ aws_region }}" | docker login --username AWS --password-stdin "262399703539.dkr.ecr.eu-central-1.amazonaws.com"
  register: ecr_login

- name: Display ECR login result
  debug:
    var: ecr_login.stdout