- name: Ensure local deploy directory exists
  delegate_to: localhost
  file:
    path: "{{ artifact_path }}/k8s-utils"
    state: directory

- name: Copy k3s binary to /usr/local/bin
  copy:
    src: "{{ artifact_path }}/k8s-utils/k3s"
    dest: /usr/local/bin/k3s
    mode: '0755'
  become: yes

- name: Copy the local k3s installer script to the remote host
  copy:
    src: "{{ artifact_path }}/k8s-utils/k3s_install.sh"
    dest: /tmp/k3s_install.sh
    mode: '0755'
  become: yes
