- name: Ensure local deploy directory exists
  delegate_to: localhost
  file:
    path: "{{ artifact_path }}/k8s-utils"
    state: directory

- name: Check if {{ item.name }} exists on local deploy directory
  stat:
    path: "{{ artifact_path }}/k8s-utils/{{ item.name }}"
  register: local_tool_file
  delegate_to: localhost

- name: Download {{ item.name }} on local host if not exists
  delegate_to: localhost
  get_url:
    url: "{{ item.url }}"
    dest: "{{ artifact_path }}/k8s-utils/{{ item.name }}"
    mode: '0755'
    validate_certs: no
  when: not local_tool_file.stat.exists
