---
- import_tasks: copy_files.yml

- name: Install k3s server if required
  import_tasks: install_server.yml
  when: k3s_mode == server

- name: Install k3s agent if required
  import_tasks: install_agent.yml
  when: k3s_mode == agent
