apiVersion: v1
kind: Namespace
metadata:
  name: airflow
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
  namespace: airflow
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/prisma/shaked/config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: report-pv
  namespace: airflow
spec:
  storageClassName: openebs-zfspv
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: coordinates-pv
  namespace: airflow
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/prisma/shaked/coordinates"