apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/prisma/shaked/config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: report-pv
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: openebs-zfspv
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: coordinates-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/prisma/shaked/coordinates"