apiVersion: v1
kind: Namespace
metadata:
  name: airflow
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: shaked-onprem-secret
  namespace: airflow
data:
  db_host: MTAuMjAuMTAuMTA0
  db_password: cG9zdGdyZXM=
  db_username: cG9zdGdyZXM=