images:
  airflow:
    repository: localhost:5000/shaked-airflow
    tag: version19

env:
  - name: AIRFLOW__CORE__PARALLELISM
    value: "150"
  - name: DEV_CONFIG
    value: "/opt/airflow/dags/repo/config"
  - name: DEV_HOME
    value: "/opt/airflow/dags/repo"
  - name: DEV_LOGS
    value: "/opt/airflow/dags/repo/logs"
  - name: PYTHONPATH
    value: "/opt/airflow/src/scripts:/opt/airflow/dags:/opt/airflow:/opt/airflow/src:/usr/local/lib/python3.9/site-packages"
  - name: AIRFLOW__WEBSERVER__NAVBAR_COLOR
    value: "#fff0e6"
  - name: AIRFLOW__WEBSERVER__NAVBAR_LOGO_TEXT_COLOR
    value: "#51504f"
  - name: AIRFLOW__WEBSERVER__NAVBAR_TEXT_COLOR
    value: "#51504f"
  - name: AIRFLOW__WEBSERVER__NAVBAR_TEXT_HOVER_COLOR
    value: "#51504f"
  - name: AIRFLOW__WEBSERVER__INSTANCE_NAME
    value: "Airflow Shaked"
  - name: RUNNING_ENV
    value: dev
  - name: AIRFLOW__WEBSERVER__BASE_URL
    value: http://data_dev.internal:8080

secret:
  - envName: DB_HOST
    secretName: shaked-onprem-secret
    secretKey: db_host
  - envName: DB_USERNAME
    secretName: shaked-onprem-secret
    secretKey: db_username
  - envName: DB_PASSWORD
    secretName: shaked-onprem-secret
    secretKey: db_password

workers:
  resources:
    limits:
     cpu: 4
     memory: 16Gi
    requests:
     cpu: 2
     memory: 1Gi
  extraVolumes:
    - name: config-volume
      persistentVolumeClaim:
        claimName: config-pv
    - name: report-volume
      persistentVolumeClaim:
        claimName: report-pv
    - name: coordinates-volume
      persistentVolumeClaim:
          claimName: coordinates-pv
  extraVolumeMounts:
    - name: config-volume
      mountPath: "/app/config"
    - name: report-volume
      mountPath: "/app/report"
    - name: coordinates-volume
      mountPath: "/app/report/coordinates"
      
  volumeClaimTemplates:
    - metadata:
        name: config-volume
      spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 100Mi
          storageClassName: "" 
          volumeName: config-pv

    - metadata:
        name: report-volume
      spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 300Gi
          storageClassName: "openebs-zfspv"
          volumeName: report-pv

    - metadata:
        name: coordinates-volume
      spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 100Mi
          storageClassName: ""
          volumeName: coordinates-pv