---
- name: Ensure offline deploy directory exists
  file:
    path: "{{ artifact_path }}/os-utils/"
    state: directory
    mode: '0755'

- name: Ensure offline deploy directory exists
  file:
    path: "{{ artifact_path }}/k8s-utils/"
    state: directory
    mode: '0755'

- name: Install each os tool
  include_tasks: install_os_tool.yml
  loop: "{{ os_tools }}"
  loop_control:
    loop_var: item

- name: Install each k8s tool
  include_tasks: install_k8s_tool.yml
  loop: "{{ k8s_tools }}"
  loop_control:
    loop_var: item
