---
- name: Process data transfer for each entry
  block:
    - include_tasks: helm_template.yml
    - include_tasks: extract_and_apply_pvc.yml
    - include_tasks: data_transfer.yml
  loop: "{{ data_transfer }}"
  loop_control:
    loop_var: dt
  vars:
    chart_name: "{{ dt.chart_name }}"        
    release_name: "{{ dt.release_name }}"            
    stack_path: "{{ artifact_path }}/linux-infra/stacks/{{ dt.stack_name }}"
    pvc_name: "{{ dt.pvc_name }}"
    host_mount: "{{ dt.host_mount }}"
    host_path: "{{ dt.host_path }}"
    dest_path: "{{ dt.dest_path }}"
    linux_user_name: "{{ linux_user_name }}"
    project_name: "{{ project_name }}"
    three_first_octets: "{{ three_first_octets }}"
    artifact_path: "{{ artifact_path }}"
    container_name: "data-transfer-{{ pvc_name }}"
    pod_name: "data-transfer-{{ pvc_name }}"
