{{- $offlineDeploy := (env "OFFLINE_DEPLOY" | default "offline_deploy") -}}
{{- $subnetOctet := (env "SUBNET_OCTET" | default "70") -}}

releases:
  - name: event-exporter
    namespace: elk
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/kubernetes-event-exporter
    wait: true
    timeout: 600
    values:
      - event-exporter/values.yaml

  - name: elasticsearch
    namespace: elk
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/elasticsearch
    timeout: 600
    hooks:
    - events: ["presync"]
      showlogs: true
      command: "kubectl"
      args: ["apply", "-f", "elasticsearch/snapshots-pvc.yml"]
    - events: [postsync]
      command: kubectl
      args: ["wait", "--for=condition=Ready", "pod", "-l", "release=elasticsearch", "--timeout=600s"]
    values:
      - elasticsearch/values.yaml
      - service:
          loadBalancerIP: 10.10.{{ $subnetOctet }}.106

  - name: kibana
    namespace: elk
    needs: [elasticsearch]
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/kibana
    wait: true
    timeout: 600
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "bash"
        args: ["./scripts/update_kibana.sh"]
    values:
      - kibana/values.yaml

  - name: logstash
    namespace: elk
    needs: [elasticsearch]
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/logstash
    wait: true
    timeout: 600
    values:
      - logstash/values.yaml

  - name: filebeat
    namespace: elk
    needs: [elasticsearch]
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/filebeat
    wait: true
    timeout: 600
    values:
      - filebeat/values.yaml

  - name: curator
    namespace: elk
    needs: [elasticsearch]
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/curator
    wait: true