environments:
  default:
    values:
      - subnetOctet: {{ env "SUBNET_OCTET" | default "70" }}

releases:
  - name: event-exporter
    namespace: elk
    path: /home/prisma/offline_deploy/helm_charts/kubernetes-event-exporter 
    wait: true
    timeout: 600
    values:
      - event-exporter/values.yaml

  - name: elasticsearch
    namespace: elk
    path: /home/prisma/offline_deploy/helm_charts/elasticsearch   
    wait: true
    timeout: 600
    values:
      - elasticsearch/values.yaml

  - name: kibana
    namespace: elk
    needs: [elasticsearch]
    path: /home/prisma/offline_deploy/helm_charts/kibana
    wait: true
    timeout: 600
    hooks:
      - events: ["postSync"]
        showlogs: true
        command: "bash"
        env:
          - name: SUBNET_OCTET
            value: "{{ .Values.subnetOctet }}"
        args:
          - "./scripts/update_kibana.sh"
    values:
      - kibana/values.yaml

  - name: logstash
    namespace: elk
    needs: [elasticsearch]
    path: /home/prisma/offline_deploy/helm_charts/logstash             
    wait: true
    timeout: 600
    values:
      - logstash/values.yaml

  - name: filebeat
    namespace: elk
    needs: [elasticsearch]
    path: /home/prisma/offline_deploy/helm_charts/filebeat               
    wait: true
    timeout: 600
    values:
      - filebeat/values.yaml

  - name: curator
    namespace: elk
    needs: [elasticsearch]
    path: /home/prisma/offline_deploy/helm_charts/curator               
    wait: true
    timeout: 600