{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tileserver-gl.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "tileserver-gl.name" . }}
    helm.sh/chart: {{ include "tileserver-gl.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  rules:
    - http:
        paths:
        {{- range .Values.ingress.paths }}
          - path: {{ . }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "tileserver-gl.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
        {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
          - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
