apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tileserver-pvc
  namespace: map-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: tileserver-pv