---
# tasks/main.yml

#########################################
# 1. Ensure directories exist and debug input
#########################################
- name: Debug k8s_tools variable
  debug:
    var: k8s_tools

- name: Ensure offline deploy directory exists
  file:
    path: /root/offline_deploy/k8s-utils
    state: directory
    mode: '0755'
  become: yes

- name: Create temporary directory for tool installation
  file:
    path: /tmp/k8s-tools
    state: directory
    mode: '0755'
  become: yes

#########################################
# 2. Download Tools (if not already present)
#########################################
- name: Check if the tool file already exists
  stat:
    path: "/root/offline_deploy/k8s-utils/{{ item.version | basename }}"
  register: tool_file
  loop: "{{ k8s_tools }}"
  loop_control:
    label: "{{ item.name }}"
    index_var: tool_index

- name: Download missing tool files
  get_url:
    url: "{{ item.version }}"
    dest: "/root/offline_deploy/k8s-utils/{{ item.version | basename }}"
    mode: "{{ (item.version | basename) is match('.*\\.tar\\.gz') | ternary('0644','0755') }}"
    validate_certs: no
  when: not tool_file.results[tool_index].stat.exists
  loop: "{{ k8s_tools }}"
  loop_control:
    label: "{{ item.name }}"
    index_var: tool_index


#########################################
# 3. Install Tools by including per-tool tasks
#########################################
- name: Install each k8s tool offline
  include_tasks: install_tool.yml
  loop: "{{ k8s_tools }}"
  loop_control:
    label: "{{ item.name }}"

#########################################
# 4. Cleanup temporary directory
#########################################
- name: Remove temporary directory
  file:
    path: /tmp/k8s-tools
    state: absent
  become: yes
