- name: Debug api_host value
  debug:
    var: "{{ (vm_role == 'master') | ternary(versions_data.configurations.masternode_ip, versions_data.configurations.workernode_ip) }}"
- name: Create Virtual Machine on Proxmox
  proxmox_kvm:
    api_host: "{{ (vm_role == 'master') | ternary(versions_data.configurations.masternode_ip, versions_data.configurations.workernode_ip) }}"
    api_user: root@pam
    api_token_id: TOKEN_ID
    api_token_secret: TOKEN_SECRET
    validate_certs: no
    name: mc-serv
    node: pve6
    newid: 800
    clone: MC-server
    storage: VM-Storage
    state: present
