config:
  logLevel: info 
  logFormat: json 
  receivers:
    - name: "dump"
      file:
        path: "/dev/stdout"
        layout: 
          message: "{{ .Message }}"
          reason: "{{ .Reason }}"
          type: "{{ .Type }}"
          count: "{{ .Count }}"
          kind: "{{ .InvolvedObject.Kind }}"
          name: "{{ .InvolvedObject.Name }}"
          namespace: "{{ .Namespace }}"
          component: "{{ .Source.Component }}"
          host: "{{ .Source.Host }}"
  route:
    routes:
      - match:
          - receiver: "dump"  
        types: 
          - Normal
          - Warning
          - Error