{{- $offlineDeploy := (env "OFFLINE_DEPLOY" | default "offline_deploy") -}}
{{- $linuxUser := (env "LINUX_USER" | default "prisma") -}}

releases:
  - name: postgres-shaked
    namespace: postgres-shaked
    chart: /home/{{ $linuxUser}}/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/postgres
    timeout: 600      
    values:
      - postgres/values.yml.gotmpl
      
  - name: airflow
    namespace: airflow
    chart: /home/{{ $linuxUser}}/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/airflow       
    wait: true
    timeout: 600
    values:
      - airflow/values.yml
    
