{{- $artifactPath := (env "ARTIFACT_PATH" | default "prisma") -}}

releases:
  - name: postgres-shaked
    namespace: postgres-shaked
    chart: {{ $artifactPath }}/helm_charts/downloaded_helm_charts/postgresql
    timeout: 600      
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "bash"
        args: ["./postgres/scripts/database_init.sh"]
    values:
      - postgres/values.yml.gotmpl
      
  - name: airflow
    namespace: airflow-control-center
    chart: {{ $artifactPath }}/helm_charts/downloaded_helm_charts/airflow       
    timeout: 600
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "bash"
        args: ["./airflow/scripts/add_airflow_prerequisites.sh"] 
    values:
      - airflow/values.yml.gotmpl
    
  - name: map-server
    namespace: map-server
    chart: {{ $artifactPath }}/helm_charts/downloaded_helm_charts/tileserver       
    timeout: 600
    values:
      - tileserver/values.yml.gotmpl
  
  - name: control-server
    namespace: airflow-control-center
    chart: {{ $artifactPath }}/helm_charts/downloaded_helm_charts/airflow       
    timeout: 600
    values:
      - control-server/values.yml.gotmpl
      - control-server/extra-manifests.yml.gotmpl
    
