{{- $offlineDeploy := (env "OFFLINE_DEPLOY" | default "offline_deploy") -}}
{{- $linuxUser := (env "LINUX_USER" | default "prisma") -}}

releases:
  - name: postgres-shaked
    namespace: postgres-shaked
    chart: /home/{{ $linuxUser}}/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/postgresql
    timeout: 600      
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "bash"
        args: ["./postgres/scripts/database_init.sh"]
    values:
      - postgres/values.yml.gotmpl
      
  - name: airflow
    namespace: airflow
    chart: /home/{{ $linuxUser}}/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/airflow       
    timeout: 600
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "bash"
        args: ["./airflow/scripts/add_airflow_prerequisites.sh"] 
    values:
      - airflow/values.yml.gotmpl
    
  - name: map-server
    namespace: airflow
    chart: /home/{{ $linuxUser}}/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/tileserver       
    timeout: 600
    values:
      - tileserver/values.yml.gotmpl
  
  - name: map-server
    namespace: airflow
    chart: /home/{{ $linuxUser}}/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/airflow       
    timeout: 600
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args: ["-f", "apply", "control-center/extra-manifests.yml.gotmpl"] 
    values:
      - airflow/values.yml.gotmpl
    
