{{- $artifactPath := (env "ARTIFACT_PATH" | default "prisma") -}}
{{- $project_name := (env "PROJECT_NAME" | default "shaked") -}}

releases:
  - name: openebs
    namespace: openebs
    chart: {{ $artifactPath }}/helm_charts/downloaded_helm_charts/openebs       
    wait: true
    timeout: 10
    values:
      - openebs/values.yml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "openebs/storageclass.yml"]      

  - name: ingress-nginx
    namespace: kube-system
    chart: {{ $artifactPath }}/helm_charts/downloaded_helm_charts/ingress-nginx
    timeout: 10      
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "bash"
        args: ["./scripts/create_tls.sh"]
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args: ["wait", "--for=condition=Ready", "pod", "-n", "kube-system", "-l", "app.kubernetes.io/name=ingress-nginx", "--timeout=10s"]
    values:
      - ingress-nginx/values.yml.gotmpl

  - name: metallb
    namespace: metallb
    chart: {{ $artifactPath }}/helm_charts/downloaded_helm_charts/metallb      
    wait: true
    timeout: 10  
    values:
      - metallb/values.yml.gotmpl

  - name: pihole
    namespace: pihole
    chart: {{ $artifactPath }}/helm_charts/downloaded_helm_charts/pihole      
    timeout: 10
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args: ["wait", "--for=condition=Ready", "pod", "-n", "pihole", "-l", "release=pihole", "--timeout=10s"]
    values:
      - pihole/values.yml.gotmpl
      - pihole/projects/{{ $project_name }}/values.yml.gotmpl
    
