{{- $offlineDeploy := (env "OFFLINE_DEPLOY" | default "offline_deploy") -}}
{{- $subnetOctet := (env "SUBNET_OCTET" | default "70") -}}

releases:
  - name: openebs
    namespace: openebs
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/openebs       # Local chart for OpenEBS
    wait: true
    timeout: 600
    values:
      - openebs/values.yml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "openebs/storageclass.yml"

  - name: nginx-controller
    namespace: kube-system
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/ingress-nginx
    timeout: 600               
    values:
      - ingress-nginx/values.yml
      - controller:
          service:
            loadBalancerIP: "10.10.{{ $subnetOctet }}.100"

  - name: metallb
    namespace: metallb
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/metallb      
    wait: true
    timeout: 600  
    values:
      - metallb:
          addresses: 
          - "10.10.70.100-10.10.{{ $subnetOctet }}.120"
          - "10.10.{{ $subnetOctet }}.50/32"

  - name: pihole
    namespace: pihole
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/pihole      
    wait: true
    timeout: 600
    values:
      - pihole/values.yml
      - serviceDns:
          loadBalancerIP: "10.10.{{ $subnetOctet }}.50"
        serviceWeb:
          loadBalancerIP: "10.10.{{ $subnetOctet }}.50"
