---
- name: Offline Installation Playbook
  hosts: all_vms
  become: true
  gather_facts: true

  roles:
    - role: offline-apt-repo
      when: enable_offline_apt_repo | default(false)

    - role: apt-install
      when: enable_apt_install | default(false)
      vars:
       apt_packages: "{{ merged_configurations.components.apt_packages | default([]) }}"

    - role: gpu-driver-install
      when: enable_gpu_driver_install | default(false)
      vars:
       gpu_settings: "{{ versions_data.components.gpu_drivers | default([]) }}"

    - role: gpu-driver-uninstall
      when: enable_gpu_driver_uninstall | default(false)
      vars:
       gpu_settings: "{{ versions_data.components.gpu_drivers | default([]) }}"

#    - role: network-setup
#      when: enable_network_setup | default(false)

    - role: configure-registry-mirroring
      when: enable_configure_registry_mirroring | default(false)

    - role: setup-local-docker-registry
      when: enable_setup_local_docker_spec | default(false)

    - role: helm-install
      when: enable_helm_install | default(false)

