---
- name: Offline Installation Playbook
  hosts: all_vms
  become: true
  gather_facts: true

  roles:
    - role: offline-apt-repo
      when: enable_offline_apt_repo | default(false)
      tags: apt
      vars:
        artifact_path: "{{ spec.configurations.artifact_path }}"

    - role: apt-install
      when: enable_apt_install | default(false)
      vars:
       apt_packages: "{{ spec.components.apt_packages | default([]) }}"
      tags: apt

    - role: drivers-install
      when: enable_drivers_install | default(false)
      vars:
       drivers: "{{ spec.components.drivers | default([]) }}"
       artifact_path: "{{ spec.configurations.artifact_path }}"
      tags: install-drivers

    - role: os-tools-install
      when: enable_os_tools_install | default(false)
      vars:
        os_tools: "{{ spec.components.os_tools }}"
        k8s_tools: "{{ spec.components.k8s_tools }}"
        artifact_path: "{{ spec.configurations.artifact_path }}"

    - role: gpu-driver-uninstall
      when: enable_gpu_driver_uninstall | default(false)
      tags: uninstall-gpu

    - role: setup-local-docker-registry
      when: enable_setup_local_docker_registry | default(false)
      vars:
        docker_images: "{{  spec.components.docker_spec.docker_images }}"
        docker_registry_address: "{{  spec.components.docker_spec.docker_registry_address }}"
        artifact_path: "{{ spec.configurations.artifact_path }}"

    - role: k3s-install
      when: enable_k3s_install | default(false)
      vars:
        master_node_ip: "{{ spec.configurations.master_node_ip }}"
        k3s_tools: "{{ spec.components.k3s_tools }}"
        artifact_path: "{{ spec.configurations.artifact_path }}"

    - role: configure-registry-mirroring
      when: enable_configure_registry_mirroring | default(false)
      vars:
       docker_registry_address: "{{ spec.components.docker_spec.docker_registry_address }}"
    
    - role: helm-install
      when: enable_helm_install | default(false)
      vars: 
        linux_user_name: "{{ spec.configurations.linux_user_name }}"
        artifact_path: "{{ spec.configurations.artifact_path }}"
        helm_charts: "{{ spec.components.helm_spec.helm_charts }}"
        project_name: "{{ spec.components.helm_spec.project_name }}"
        helm_repos: "{{ spec.components.helm_spec.helm_repos }}"
        three_first_octets: "{{ spec.components.helm_spec.three_first_octets }}"
        branch_name: "{{ spec.components.helm_spec.branch_name  }}"

