---
- name: Offline Installation Playbook
  hosts: all
  become: true
  gather_facts: true

  # 1) First, load the site’s versions.yml
  pre_tasks:
    - name: Debug versions data
      debug:
        var: configuration
    
        
  roles:
    - role: create-template
      vars:
        template_vmid: 9000
        template_name: "template-name"
        cloud_init_user: "prisma"
        cloud_init_password: "prisma"
        net_bridge: "{{ configuration.net_bridge }}"
        # memory: 2048
        # cores: 2
        # scsihw: virtio-scsi-pci
        proxmox_storage: "local-lvm"
        cloud_image: "/var/lib/vz/template/iso/noble-server-cloudimg-amd64.img"

    - role: create-vms
      vars:
        proxmox_host_ip: "{{ configuration.proxmox_host_ip }}"
        proxmox_user: "{{ configuration.proxmox_user }}"
        proxmox_user_password: "{{ configuration.proxmox_user_password }}"
        proxmox_node: "{{ configuration.proxmox_node }}"
        template_name: "template-name"
        proxmox_storage: "local-lvm"
        cloud_image: "/var/lib/vz/template/iso/noble-server-cloudimg-amd64.img"
        vms: "{{ configuration.vms }}"

