---
- name: Load machine configuration and add hosts dynamically
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Add each machine from manifest to dynamic inventory
      add_host:
        name: "{{ item.key }}"
        ansible_host: "{{ item.value.ansible_host }}"
        ansible_user: "{{ item.value.ansible_user }}"
        ansible_password: "{{ item.value.ansible_password }}"
        configuration: "{{ item.value }}"
      loop: "{{ machines | dict2items }}"


- name: Offline Installation Playbook
  hosts: "{{ machines.keys() }}"
  become: true
  gather_facts: true
  pre_tasks:
    - name: Set machine configuration fact
      set_fact:
        machine_config: "{{ hostvars[inventory_hostname].configuration }}"
        machine_name: "{{ inventory_hostname }}"

    - name: Debug versions data
      debug:
        var: machine_config.net_bridge

    - name: Debug versions dasdasdata
      debug:
        var: machine_name


# # add default vars

  roles:
    - role: create-template
      vars:
        # template_vmid: 
        template_vmid: "{{ machine_config.template_vmid }}"
        template_name: "{{ machine_name }}-template"
        cloud_init_user: "prisma"
        cloud_init_password: "prisma"
        net_bridge: "{{ machine_config.net_bridge }}"
        scsihw: virtio-scsi-pci
        memory: 2048
        cores: 2
        proxmox_storage: "local-lvm"
        cloud_image: "/var/lib/vz/template/iso/noble-server-cloudimg-amd64.img"

# # add download if needed

    - role: create-vms
      vars:
        proxmox_host_ip: "{{ machine_config.proxmox_host_ip }}"
        proxmox_user: "{{ machine_config.proxmox_user }}"
        proxmox_user_password: "{{ machine_config.proxmox_user_password }}"
        proxmox_node: "{{ machine_config.proxmox_node }}"
        template_name: "{{ machine_name }}-template"
        proxmox_storage: "local-lvm"
        vms: "{{ configuration.vms }}"

