- name: Check existence of helm chart folders
  stat:
    path: "{{ artifact_path }}/helm_charts/downloaded_helm_charts/openebs"
  register: openebs_chart_folder

- name: Log if any helm chart folders are missing
  fail:
    msg: "The openebs helm chart folder is missing"
  when: not openebs_chart_folder.stat.exists 

- block:
    - name: Run helmfile sync with injected environment variables using -f flag
      command: "helmfile sync --concurrency=1 --skip-deps"
      args:
        chdir: "{{ artifact_path }}/linux-infra/stacks/storage-stack"
      environment:
        ARTIFACT_PATH: "{{ artifact_path }}"
        KUBECONFIG: "/home/{{ linux_user_name }}/.kube/config"
      register: helmfile_output

  always:
    - name: Ensure output directory exists on the controller
      file:
        path: "{{ artifact_path }}/helmfile_outputs"
        state: directory
        mode: '0755'

    - name: Write helmfile command output 
      copy:
        dest: "{{ artifact_path }}/helmfile_outputs/helmfile_output.txt"
        content: "{{ helmfile_output.stderr }}"