replicaCount: 1
maxUnavailable: 0

adminPassword: "prisma"

serviceDhcp:
  enabled: false

serviceDns:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole

serviceWeb:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistentVolumeClaim:
  enabled: true
  storageClass: "openebs-zfspv"

image:
  repository: localhost:5000/pihole/pihole
  tag: 2024.07.0
  pullPolicy: IfNotPresent
