apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
data:
  curator.yml: |
    elasticsearch:
      client:
        hosts:
          - https://elasticsearch-master:9200
        cloud_id:
        ca_certs:
        client_cert:
        client_key:
        verify_certs: False
        request_timeout: 30
      other_settings:
        master_only: False
        username: elastic
        password: prisma
        api_key:
          id:
          api_key:
          token:

    logging:
      loglevel: INFO
      logfile: /dev/stdout
      logformat: default
      blacklist: ['elasticsearch']
  delete_old_indices.yml: |
    actions:
      1:
        action: delete_indices
        description: "Delete oldest indices when storage usage exceeds {{ .Values.curator.storage.tresholdSize }} GB"
        options:
          ignore_empty_list: True
          timeout_override: 300
          continue_if_exception: False
          disable_action: False
        filters:
          - filtertype: pattern
            kind: prefix
            value: logstash-logs-
          - filtertype: space
            disk_space: {{ .Values.curator.storage.tresholdSize }}
            use_age: True
            source: creation_date

