- name: Add environment variables to the user's .bashrc file only once
  blockinfile:
    path: "/home/{{ linux_user_name }}/.bashrc"
    create: yes
    marker: "# {mark} ANSIBLE MANAGED ENV VARS"
    block: |
      export PROJECT_NAME="{{ project_name }}"
      export LINUX_USER="{{ linux_user_name }}"
      export THREE_FIRST_OCTETS="{{ three_first_octets }}"
      export ARTIFACT_PATH="{{ artifact_path }}"