---
- name: Process each Docker image in offline mode
  include_tasks: load.yml
  when: installation_mode == 'offline'
  loop: "{{ docker_images }}"
  loop_control:
    loop_var: image

- name: Process each Docker image in online mode
  include_tasks: pull.yml
  when: installation_mode == 'online'
  loop: "{{ docker_images }}"
  loop_control:
    loop_var: image
