- name: AWS ECR Login if image is hosted in AWS ECR
  docker_login:
    registry_url: "262399703539.dkr.ecr.eu-central-1.amazonaws.com"
    username: "AWS"
    password: "{{ lookup('pipe', 'aws ecr get-login-password --region eu-central-1') }}"
  when: image.name is search('^262399703539.dkr.ecr.eu-central-1.amazonaws.com')
  register: aws_login

- name: Pull Docker image {{ image.name }}:{{ image.version }} from Docker Hub
  docker_image:
    name: "{{ image.name }}"
    tag: "{{ image.version }}"
    source: pull
