---
- name: Offline Installation Playbook
  hosts: shaked
  become: true
  gather_facts: true

  # 1) First, load the site’s versions.yml
  pre_tasks:
    - name: Show filepath
      debug:
        msg: "{{ versions_file }}"

    - name: Load versions file
      include_vars:
        file: "{{ versions_file }}"
        name: versions_data
    
    - name: Debug enable_docker_registry value
      debug:
        var: versions_data.dockerRegistryAddress

  roles:
    - role: create-vms
      when: enable_create_vms | default(true)
      vars:
        proxmox_host_ip: "{{ merged_configurations.proxmox_host_ip }}"
        proxmox_user: "{{ merged_configurations.proxmox_user }}"
        proxmox_user_password: "{{ merged_configurations.proxmox_user_password }}"
        proxmox_node: "{{ merged_configurations.proxmox_node }}"
        vms: "{{ merged_configurations.vms }}"

    - role: offline-apt-repo
      when: enable_offline_apt_repo | default(false)

    - role: apt-install
      when: enable_apt_install | default(false)
      vars:
       apt_packages: "{{ merged_configurations.components.apt_packages | default([]) }}"

#    - role: network-setup
#      when: enable_network_setup | default(false)

    # 4) Docker registry setup if enabled
    - role: docker-registry
      when: enable_docker_registry | default(false)

    # 5) Helm install if enabled (pass helm_charts from versions_data)
    - role: helm-install
      when: enable_helm_install | default(false)
     

