{{- $offlineDeploy := (env "OFFLINE_DEPLOY" | default "offline_deploy") -}}
{{- $subnetOctet := (env "SUBNET_OCTET" | default "70") -}}

releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/kube-prometheus-stack
    values:
      - prometheus-stack/values.yaml

  - name: telegraf
    namespace: monitoring
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/telegraf
    values:
      - telegraf/values.yaml
      # - telegraf/{{ env "PROJECT_NAME" | default "default_project" }}/values.yml

  - name: helm-dashboard
    namespace: kube-system
    path: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/helm-dashboard
    values:
      - helm-dashboard/values.yaml
      - service:
          loadBalancerIP: 10.10.{{ $subnetOctet }}.106

  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/kubernetes-dashboard
    values:
      - kubernetes-dashboard/values.yaml
