environments:
  default:
    values:
      - subnetOctet: {{ env "SUBNET_OCTET" | default "70" }}

releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: /home/prisma/offline_deploy/helm_charts/kube-prometheus-stack
    values:
      - prometheus-stack/values.yaml

  - name: telegraf
    namespace: monitoring
    chart: /home/prisma/offline_deploy/helm_charts/telegraf
    values:
      - telegraf/values.yaml

  # - name: helm-dashboard
  #   namespace: kube-system
  #   path: /home/prisma/offline_deploy/helm_charts/helm-dashboard
  #   values:
  #     - helm-dashboard/values.yaml

  # - name: kubernetes-dashboard
  #   namespace: kubernetes-dashboard
  #   chart: /home/prisma/offline_deploy/helm_charts/kubernetes-dashboard
  #   values:
  #     - kubernetes-dashboard/values.yaml
