{{- $offlineDeploy := (env "OFFLINE_DEPLOY" | default "offline_deploy") -}}

releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/kube-prometheus-stack
    values:
      - prometheus-stack/values.yaml

  - name: telegraf
    namespace: monitoring
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/telegraf
    values:
      - telegraf/values.yaml

  - name: helm-dashboard
    namespace: kube-system
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/helm-dashboard
    values:
      - helm-dashboard/values.yaml.gotmpl

  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/kubernetes-dashboard
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "kubernetes-dashboard/auth.yaml"]  
    values:
      - kubernetes-dashboard/values.yaml.gotmpl
