---
# handlers/main.yml

- name: reload systemd daemon and restart k3s
  become: yes
  block:
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Restart k3s service
      systemd:
        name: k3s
        state: restarted
