replicaCount: 1

palyer_enabled: true

ingress:
  enabled: true
  ingressClassName: nginx
  rules:
    - host: example.com
      paths:
        - /
  tls: []

serviceAccountName: focus-server-sa

image:
  repository: "262399703539.dkr.ecr.eu-central-1.amazonaws.com/pzlinux"
  tag: "10.7.104"
  pullPolicy: IfNotPresent

workingDir: "/home/prisma"
command:
  - "./debug-codebase/active-python-env.sh"
  - "-m"
  - "focus_server"

service:
  type: ClusterIP
  port: 5000

env:
  PZ_IMAGE_TAG: "10.7.104"
  PRISMA_CONFIG: "/home/prisma/pz/config/"

volumeMounts:
  debugEnv:
    mountPath: "/home/prisma/debug-codebase"
  prismaConfig:
    mountPath: "/home/prisma/pz/config"

volumes:
  debugEnv:
    path: "/home/prisma/debug-codebase"
  prismaConfig:
    path: "/home/prisma/pz/config"
  pythonPackages:
    path: "/home/prisma/.local/lib/python3.10/site-packages"

terminationGracePeriodSeconds: 30

