---
- name: Install gcc-9
  apt:
    name: gcc-9
    state: present
- name: Install CUDA driver from runfile
  command: "sh /home/prisma/cuda_12.8.0_570.86.10_linux.run --silent --driver"
  args:
    # Using 'creates' ensures idempotency by skipping the install if nvidia-smi already exists.
    creates: "/usr/bin/nvidia-smi"
  register: runfile_install

- name: Display runfile installation result
  debug:
    var: runfile_install
