---
- name: Copy run file from host to user
  copy:
    src: /root/offline_deploy/NVIDIA-Linux-x86_64-570.124.04.run
    dest: /home/prisma/NVIDIA-Linux-x86_64-570.124.04.run
    mode: '0755'
- name: Install gcc-9
  apt:
    name: gcc-9
    state: present

- name: Disable Nouveau driver by blacklisting it
  copy:
    dest: /etc/modprobe.d/nvidia-installer-disable-nouveau.conf
    content: |
      blacklist nouveau
      options nouveau modeset=0
    mode: '0644'
  notify: Update initramfs

- name: Update initramfs (Debian/Ubuntu)
  command: update-initramfs -u
  become: true
  when: ansible_os_family == "Debian"

- name: Reboot the system to apply Nouveau changes
  reboot:
    reboot_timeout: 600
  when: do_reboot | default(true)
  # Uncomment the following line if you need to force a reboot after disabling Nouveau:
  # when: true

- name: Install CUDA driver from runfile
  command: "sh /home/prisma/NVIDIA-Linux-x86_64-570.124.04.run --dkms --silent"
  args:
    # Using 'creates' ensures idempotency by skipping the install if nvidia-smi already exists.
    creates: "/usr/bin/nvidia-smi"
  register: runfile_install

- name: Display runfile installation result
  debug:
    var: runfile_install

- name: Reboot the system to load the new driver
  reboot:
    reboot_timeout: 600
  when: runfile_install.changed and do_reboot | default(false)
