---
- name: Verify the partition device exists
  stat:
    path: "{{ zfs_configuration.partition_configuration.device }}"
  register: device_stat
  failed_when: not device_stat.stat.exists

- name: Create partition using community.general.parted
  community.general.parted:
    device: "{{ zfs_configuration.partition_configuration.device }}"
    number: "{{ zfs_configuration.partition_configuration.number }}"
    state: present
    label: "{{ zfs_configuration.partition_configuration.label }}"
    part_type: "{{ zfs_configuration.partition_configuration.part_type }}"
    fs_type: "{{ zfs_configuration.partition_configuration.fs_type }}"
    part_start: "{{ zfs_configuration.partition_configuration.start }}"
    part_end: "{{ zfs_configuration.partition_configuration.end }}"
  become: yes
  register: parted_result

- name: Debug partition creation result
  debug:
    var: parted_result
