---
- name: Create ZFS zpools
  community.general.zpool:
    name: "{{ item.zpool_name }}"
    state: present
    disks: "{{ item.zpool_device }}"
  loop: "{{ zfs_configuration.zpools }}"
  become: yes
  register: zpool_results

- name: Debug zpool creation results
  debug:
    var: zpool_results
