# roles/create_zfs_dataset/tasks/zpool.yml

- name: Create ZFS pool {{ zfs_configuration.zpool_name }}
  command: >
    zpool create {{ zfs_configuration.zpool_name }} {{ zfs_configuration.zpool_device }}
  args:
    creates: "/{{ zfs_configuration.zpool_name }}"
  # The "creates" parameter prevents recreating the pool if it already exists.
