---
- name: Remove any existing VM with template ID
  shell: |
    qm unlock {{ template_vmid }} || true
    qm destroy {{ template_vmid }} || true
  ignore_errors: true


- name: Check if bridge {{ net_bridge.name }} exists on the host
  command: ip link show {{ net_bridge.name }}
  register: bridge_check
  ignore_errors: yes

- name: Delete bridge interface {{ net_bridge.name }} if it exists
  become: yes
  # command: ip link delete {{ net_bridge.name }} type bridge
  shell: | 
    ip link set {{ net_bridge.name }} down
    brctl delbr {{ net_bridge.name }}
  when: bridge_check.rc == 0

- name: Create bridge {{ net_bridge.name }} using pvesh
  shell: >
    pvesh create /nodes/{{ proxmox_node }}/network --iface {{ net_bridge.name }} --type bridge

- name: Configure the bridge {{ net_bridge.name }} using pvesh
  shell: >
    pvesh set /nodes/{{ proxmox_node }}/network/{{ net_bridge.name }} --type bridge --cidr {{ net_bridge.cidr }} --autostart

- name: Reloading the Proxmox networking {{ net_bridge.name }} using pvesh
  shell: >
    pvesh set /nodes/{{ proxmox_node }}/network

# Handler to restart networking
# - name: Restart networking
#   become: yes
#   service:
#     name: networking
#     state: restarted



- name: Create VM with cloud-init parameters for template
  shell: |
    qm create {{ template_vmid }} \
      --name {{ template_name }} \
      --ciuser {{ cloud_init_user }} \
      --cipassword {{ cloud_init_password }} \
      --net0 virtio,bridge={{ net_bridge.name }} \
      --memory 2048 \
      --cores 2 \
      --scsihw virtio-scsi-pci \
      --ipconfig0 ip=dhcp \
      --ostype l26 \
      --agent 1
  args:
    executable: /bin/bash


- name: Import disk image into template VM
  shell: >
    qm importdisk {{ template_vmid }} {{ cloud_image }} {{ proxmox_storage }}
  register: import_disk

- name: Attach disk and add cloud-init drive to template VM
  shell: |
    qm set {{ template_vmid }} \
      --scsi0 {{ proxmox_storage }}:vm-{{ template_vmid }}-disk-0 \
      --boot order=scsi0 \
      --ide2 {{ proxmox_storage }}:cloudinit
  args:
    executable: /bin/bash


- name: Resize disk (if needed)
  shell: >
    qm resize {{ template_vmid }} scsi0 +20G
  register: resize_disk

- name: Convert VM to a template
  shell: >
    qm template {{ template_vmid }}
  register: convert_template
